##例外UnknownHostExceptionはすでに捕捉されています

- catchする例外の順番も大事っぽいな
- 広く拾うcatchは後ろの方？


##例外IOExceptionは対応するtry文の本体ではスローされません

- 例外が投げれないっぽい？